// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getEigenValues
arma::vec getEigenValues(arma::mat M);
RcppExport SEXP _MTFMextra_getEigenValues(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenValues(M));
    return rcpp_result_gen;
END_RCPP
}
// sumlogeigen
double sumlogeigen(arma::mat M);
RcppExport SEXP _MTFMextra_sumlogeigen(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sumlogeigen(M));
    return rcpp_result_gen;
END_RCPP
}
// sigmult
arma::mat sigmult(arma::mat A, arma::mat B, arma::mat C, arma::mat D);
RcppExport SEXP _MTFMextra_sigmult(SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmult(A, B, C, D));
    return rcpp_result_gen;
END_RCPP
}
// ApBmult
arma::mat ApBmult(arma::mat A, double phi, double psi);
RcppExport SEXP _MTFMextra_ApBmult(SEXP ASEXP, SEXP phiSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(ApBmult(A, phi, psi));
    return rcpp_result_gen;
END_RCPP
}
// E1helper
SEXP E1helper(arma::mat pvarj, arma::mat V, arma::mat x);
RcppExport SEXP _MTFMextra_E1helper(SEXP pvarjSEXP, SEXP VSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type pvarj(pvarjSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(E1helper(pvarj, V, x));
    return rcpp_result_gen;
END_RCPP
}
// wsum
double wsum(NumericVector x, NumericVector w);
RcppExport SEXP _MTFMextra_wsum(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(wsum(x, w));
    return rcpp_result_gen;
END_RCPP
}
// armqr
SEXP armqr(arma::mat M);
RcppExport SEXP _MTFMextra_armqr(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(armqr(M));
    return rcpp_result_gen;
END_RCPP
}
// invxxt
arma::mat invxxt(arma::mat x);
RcppExport SEXP _MTFMextra_invxxt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(invxxt(x));
    return rcpp_result_gen;
END_RCPP
}
// cpdiff
arma::mat cpdiff(arma::mat x, arma::vec w);
RcppExport SEXP _MTFMextra_cpdiff(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(cpdiff(x, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MTFMextra_getEigenValues", (DL_FUNC) &_MTFMextra_getEigenValues, 1},
    {"_MTFMextra_sumlogeigen", (DL_FUNC) &_MTFMextra_sumlogeigen, 1},
    {"_MTFMextra_sigmult", (DL_FUNC) &_MTFMextra_sigmult, 4},
    {"_MTFMextra_ApBmult", (DL_FUNC) &_MTFMextra_ApBmult, 3},
    {"_MTFMextra_E1helper", (DL_FUNC) &_MTFMextra_E1helper, 3},
    {"_MTFMextra_wsum", (DL_FUNC) &_MTFMextra_wsum, 2},
    {"_MTFMextra_armqr", (DL_FUNC) &_MTFMextra_armqr, 1},
    {"_MTFMextra_invxxt", (DL_FUNC) &_MTFMextra_invxxt, 1},
    {"_MTFMextra_cpdiff", (DL_FUNC) &_MTFMextra_cpdiff, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MTFMextra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
