# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigenValues <- function(M) {
    .Call('_MTFMextra_getEigenValues', PACKAGE = 'MTFMextra', M)
}

sumlogeigen <- function(M) {
    .Call('_MTFMextra_sumlogeigen', PACKAGE = 'MTFMextra', M)
}

sigmult <- function(A, B, C, D) {
    .Call('_MTFMextra_sigmult', PACKAGE = 'MTFMextra', A, B, C, D)
}

ApBmult <- function(A, phi, psi) {
    .Call('_MTFMextra_ApBmult', PACKAGE = 'MTFMextra', A, phi, psi)
}

E1helper <- function(pvarj, V, x) {
    .Call('_MTFMextra_E1helper', PACKAGE = 'MTFMextra', pvarj, V, x)
}

wsum <- function(x, w) {
    .Call('_MTFMextra_wsum', PACKAGE = 'MTFMextra', x, w)
}

armqr <- function(M) {
    .Call('_MTFMextra_armqr', PACKAGE = 'MTFMextra', M)
}

invxxt <- function(x) {
    .Call('_MTFMextra_invxxt', PACKAGE = 'MTFMextra', x)
}

cpdiff <- function(x, w) {
    .Call('_MTFMextra_cpdiff', PACKAGE = 'MTFMextra', x, w)
}

